# Project Information
site_name: FFXIVITA Plugins  Documentation
site_url: https://plugins.ffxivita.it/
site_description: Comprehensive documentation for FFXIVITA Plugins and Development
# repo allows for linking main repo to docs
# Uncomment to use
repo_url: https://github.com/ffxivita/DalamudPlugins/
repo_name: ffxivita/DalamudPlugins
edit_uri: "" #removes edit button and icon
copyright: Powered by <a href="https://vercel.com/?utm_source=ffxivita&utm_campaign=oss" target="_blank">
  <img src="/assets/images/vercel-logotype-light.svg" alt="Vercel Logo"></a>
# Configuration
theme:
  name: material
  # Theme Overhaul configuration. Use with caution.
  # Uncommenting custom_dir requires additional setup.
  custom_dir: overrides
  logo: assets/images/ffxivita-logo.png
  font:
    text: Inter
  palette:
    scheme: slate
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    # Temporarily deactivated to provide support for Discord browser + anchor links
    # - navigation.instant
    - navigation.top
    - navigation.tracking
    - search.suggest
    - search.highlight
    - search.share
# Plugins
plugins:
  search:
    lang: en
  # Comment out the plugin below if building docs without an internet connection.
  external-markdown: {}
  awesome-pages: {}
  tags: {}
  git-revision-date-localized:
    type: date
  mkdocs-video:
    mark: "video-embed"

 glightbox:
    touchNavigation: true
    loop: false
    effect: zoom
    width: 100%
    height: auto
    zoomable: true
    draggable: true
    skip_classes:
      - skip-lightbox
    auto_caption: false
    caption_position: bottom

extra_css:
  - css/ffxivita.css
  - css/admonitions.css
  - css/navigation.css

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ffxivita
      name: FFXIVITA on Github
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/ffxiv_it
      name: FFXIVITA on Twitter
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/FFXIVITA
      name: FFXIVITA on Facebook
    - icon: fontawesome/brands/discord
      link: https://discord.com/invite/ffxivita
      name: FFXIVITA on Discord
    - icon: fontawesome/brands/twitch
      link: https://www.twitch.tv/ffxivita
      name: FFXIVITA on Twitch
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@FFXIVITA
      name: FFXIVITA on Youtube
