# Project Information
site_name: FFXIVITA Docs
site_url: https://docs.ffxivita/
site_description: Comprehensive documentation for FFXIVITA
# repo allows for linking main repo to docs
# Uncomment to use
repo_url: https://github.com/ffxivita/Siren/
repo_name: ffxivita/Siren
edit_uri: "" #removes edit button and icon
copyright: Powered by <a href="https://vercel.com/?utm_source=ffxivita&utm_campaign=oss" target="_blank">
  <img src="/assets/images/vercel-logotype-light.svg" alt="Vercel Logo"></a>

# Configuration
theme:
  name: material
  # Theme Overhaul configuration. Use with caution.
  # Uncommenting custom_dir requires additional setup.
  custom_dir: overrides
  logo: assets/images/ffxivita.svg
  font:
    text: Inter
  palette:
    scheme: slate
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    # Temporarily deactivated to provide support for Discord browser + anchor links
    # - navigation.instant
    - navigation.top
    - navigation.tracking
    - search.suggest
    - search.highlight
    - search.share
  favicon: assets/images/ffxivita.svg

# Plugins
plugins:
  search:
    lang: en
  # Comment out the plugin below if building docs without an internet connection.
  external-markdown: {}
  awesome-pages: {}
  tags: {}
  git-revision-date-localized:
    type: date
  mkdocs-video:
    mark: "video-embed"
  glightbox:
    touchNavigation: true
    loop: false
    effect: zoom
    width: 100%
    height: auto
    zoomable: true
    draggable: true
    skip_classes:
      - skip-lightbox
    auto_caption: false
    caption_position: bottom

# Styling Front-end
extra_css:
  - stylesheets/extra.css
  - stylesheets/admonitions.css
  - stylesheets/navigation.css

# Extra Functions / Customizations
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/flybywiresim
      name: FlyByWire Simulations on Github
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/FlyByWireSim
      name: FlyByWire Simulations on Twitter
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/FlyByWireSimulations
      name: FlyByWire Simulations on Facebook
    - icon: fontawesome/brands/discord
      link: https://discord.com/invite/flybywire
      name: FlyByWire Simulations on Discord
    - icon: fontawesome/brands/twitch
      link: https://www.twitch.tv/flybywiresimulations
      name: FlyByWire Simulations on Twitch
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@FlyByWireSim
      name: FlyByWire Simulations on Youtube

# Additional Markdown Extensions to use bundled icon sets
markdown_extensions:
  meta: {} # Add front matter to a document
  admonition: {} # Makes things pretty
  pymdownx.superfences: {} # Nestled code
  attr_list: {} # Add HTML attributes and CSS classes to Markdown elements
  pymdownx.tabbed: # Content tabs
    alternate_style: true
  pymdownx.details: {} # Additional features to admonition
  pymdownx.caret: {} # Formatting Extension
  pymdownx.critic: {} # Alternate Formatting Extension
  pymdownx.mark: {} # Formatting Extension
  pymdownx.tilde: {} # Formatting Extension
  pymdownx.keys: {} # Visual keyboard keys extension
  pymdownx.tasklist:
    custom_checkbox: true
  pymdownx.emoji: # Allows emoji style inline embeds for icons
    emoji_index: !!python/name:materialx.emoji.twemoji
    emoji_generator: !!python/name:materialx.emoji.to_svg