name: Build Validation

on:
  issue_comment:
    types: [created]

jobs:
  validate:
    runs-on: ubuntu-latest
    # Check if PR, prevent running on forks and trigger comment
    if: ${{ github.event.issue.pull_request && github.repository_owner == 'ffxivita' && github.event.comment.body == 'check build' }}
    steps:
      - name: React to comment
        uses: actions/github-script@211cb3fefb35a799baa5156f9321bb774fe56294 # v5
        with:
          script: |
            const {owner, repo} = context.issue;
            github.rest.reactions.createForIssueComment({
              owner,
              repo,
              comment_id: context.payload.comment.id,
              content: "rocket",
            });
      - name: Get PR SHA
        id: sha
        uses: actions/github-script@211cb3fefb35a799baa5156f9321bb774fe56294 # v5
        with:
          result-encoding: string
          script: |
            const { owner, repo, number } = context.issue;
            const pr = await github.rest.pulls.get({
              owner,
              repo,
              pull_number: number,
            });
            return pr.data.head.sha
      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2
        with:
          ref: ${{ steps.sha.outputs.result }}
          fetch-depth: 0
      - name: Make Build
        uses: actions/setup-python@e9aba2c848f5ebd159c070c61ea2c4e2b122355e # v2
        with:
          python-version: 3.x
      - run: |
          pip install -r requirements.txt
          mkdocs build -s
      - name: Message success
        if: ${{ success() }}
        uses: actions/github-script@211cb3fefb35a799baa5156f9321bb774fe56294 # v5
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Strict Build Validated! ✅',
            });
      - name: Message failure
        if: ${{ failure() }}
        uses: actions/github-script@211cb3fefb35a799baa5156f9321bb774fe56294 # v5
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Strict Build Failed! ❌ - Please checkout this PR locally to fix the issue before merging or visit the actions tab.',
            });